Fix province icon scaling
OpenVicProject/OpenVic pull request #322
Opened 2024-12-08 22:33 UTC by Hop311

- Province icons (RGOs, crimes, national foci) are now scaled by 0.75 vertically, while capitals are still 1:1.
- Some tweaks to billboard management:
  - we only set up billboards we actually use, the others are ignored.
  - `StringName`s are used over `String`s where possible.
  - `ProvinceBillboards` enum values are used where possible rather than hardcoded strings.

2024-12-08 23:05 UTC, Nemrav requested changes
Just a couple small tweaks, nice work.

2024-12-08 23:05 UTC, Nemrav commented on game/src/Game/GameSession/BillboardManager.gd
> +enum ProvinceBillboards { NONE, INVISIBLE, RGO, CRIME, NATIONAL_FOCUS, CAPITAL }
The original intent was to represent the current state of the province billboards. Now that it also includes CAPITAL, it should be renamed something more generic like `BillboardState`. It doesn't have to be that name, just something better descriptive of what the enum is for.

2024-12-09 23:16 UTC, Hop311 commented
I think something else might be stretching our icons vertically beyond the dims we set, as Vic2 definitely scales RGO icons by exactly 0.8 vertically but in OpenVic the same value makes them look noticably taller. Similarly, Vic2 doesn't seem to stretch crime icons vertically, but ours appear slightly taller than they should even at 1:1 scale.

Also some icons aren't appearing in the correct position, e.g. the entire south coast of the UK (Plymouth, Salisbury, Southampton, Brighton and Canterbury) have their icons in different positions in Vic2 vs OpenVic.

2024-12-11 02:14 UTC, Nemrav approved these changes
Looks Good, Nice work.

2024-12-12 00:19 UTC, merged